---
- name: Disallow root login remotely
  command: >
    mysql -u {{ mysql_root_username }} -p{{ mysql_root_password }} -NBe
    "DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  changed_when: false

- name: Get list of hosts for the root user.
  command: >
    mysql -u {{ mysql_root_username }} -p{{ mysql_root_password }} -NBe
    "SELECT Host FROM mysql.user WHERE User = '{{ mysql_root_username }}' ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  changed_when: false
  check_mode: false
  when: mysql_install_packages | bool or mysql_root_password_update

- name: Get list of hosts for the anonymous user.
  command: >
    mysql -u {{ mysql_root_username }} -p{{ mysql_root_password }} -NBe
    'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false
  check_mode: false

- name: Remove anonymous MySQL users.
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines | default([]) }}"

- name: Update MySQL root password for localhost root account (5.7.x and 8.0.x).
  shell: >
    mysql -u {{ mysql_root_username }} -p{{ mysql_root_password }} -NBe
    'ALTER USER "{{ mysql_root_username }}"@"{{ item }}" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  with_items: "{{ mysql_root_hosts.stdout_lines | default([]) }}"
  when: 
    - (mysql_install_packages | bool) or mysql_root_password_update
    - "'5.7.' in mysql_cli_version.stdout or '8.0.' in mysql_cli_version.stdout"
    - inventory_hostname in groups['slave']
    
  