- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 300

- name: Download Percona Release package
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    dest: /tmp/percona-release_latest.generic_all.deb

- name: Install necessary packages and Percona Release package
  apt:
    deb: /tmp/percona-release_latest.generic_all.deb
    state: present
  become: true

- name: Setup Percona 8.0 repository
  shell: percona-release setup ps80
  args:
    creates: /etc/apt/sources.list.d/percona-ps-80-release.list
  become: true

- name: Enable Percona 8.0 repository
  shell: percona-release enable ps-80 release
  args:
    creates: /etc/apt/sources.list.d/percona-ps-80-release.list
  become: true

- name: Update apt cache after enabling Percona 8.0 repository
  apt:
    update_cache: true

- name: Install Percona Server
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - '{{ percona_packages }}'
  notify:
    - reload_percona

# - name: Ensure pymysql package
#   pip:
#     name: pymysql
#     state: present
#     executable: /usr/bin/pip3




# - name: Install passlib using pip
#   ansible.builtin.pip:
#     name: passlib
#     state: present

# ---
# - name: "Update apt cache"
#   apt:
#     update_cache: true
#     cache_valid_time: 300

# - name: Add Percona Repository
#   apt:
#     autoremove: true
#     update_cache: true
#     deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename }}_all.deb
#     state: present

# - name: "Enable Percona repository"
#   command: "percona-release setup ps-{{ version | replace('.', '') }}"
#   changed_when: true

# - name: Install Percona Server
#   apt:
#     name: "{{ item }}"
#     update_cache: true
#     state: present
#   loop:
#     - '{{ percona_packages }}'
#   notify:
#     - reload_percona

# - name: Ensure pymysql package
#   pip:
#     name: pymysql
#     state: present
